### ISSUE TITLE
htdocs alias not working - Windows Cmder

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e15-spring20#7] opened 2020-02-11 03:42 UTC
I tried creating an alias for htdocs, but I got an error:
```git
c:\xampp\htdocs
λ htdocs
'htdocs' is not recognized as an internal or external command,
operable program or batch file.

c:\xampp\htdocs
```

In c:\cmder-master\config\user_aliases.cmd, I have
```htdocs=cd c:\xampp\htdocs```

**Comment by susanBuck** [comment] 2020-02-11 16:07
@anyav77 - Can you try closing and re-opening Cmder (if you haven't already)? 

Also, can you share the full contents of your `c:\cmder-master\config\user_aliases.cmd` file? I'll plug it into my Cmder install and see if I can recreate the issue.

**Comment by anyav77** [comment] 2020-02-12 03:29
I closed and reopened the commander, and I tried it again.  It did not return an error, but it also did nothing.
```git

;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
e.=explorer .
gl=git log --oneline --all --graph --decorate  $*
ll=ls -laFG
pwd=cd
clear=cls
history=cat "%CMDER_ROOT%\config\.history"
unalias=alias /d $1
vi=vim $*
cmderr=cd /d "%CMDER_ROOT%"
vhosts=notepad c:\xampp\apache\conf\extra\httpd-vhosts.conf
hosts=elevate notepad c:\Windows\System32\drivers\etc\hosts
htdocs=cd c:\xampp\htdocs

```

**Comment by susanBuck** [comment] 2020-02-12 17:05
I copied your aliases into my `c:\cmder-master\config\user_aliases.cmd`, then restarted Cmder, and the `htdocs` alias worked:

![image](https://user-images.githubusercontent.com/237711/74358585-b32db280-4d8f-11ea-80bb-5fe1e47a22eb.png)

Given this, I don't think it's a problem in the alias configs itself.

Do any of the other aliases work? For example, if you run `hosts` does it open your hosts file in notepad?

**Comment by anyav77** [comment] 2020-02-19 00:24
Yes, the other aliases work.  I retested htdocs, and it's working now.

Could it be caused by Windows 7, perhaps?  I have to update, and I'm concerned that it may cause some issues with the software in the middle of the semester.  Do you know of any bugs that may come along?  How risky is it to upgrade vs not upgrade during the semester?

**Comment by susanBuck** [comment] 2020-02-19 17:08
Glad to hear it's working now. I can't think of a reason why the OS version would have been the cause here, but - never say never. : )

Regarding upgrading - I don't anticipate any problems - I test all the procedures on Windows 10. That being said, if you run into hiccups, you can always reach out for help.

**Closed by susanBuck** 2020-02-19 17:08 UTC
